# Generated by Django 4.2.1 on 2023-05-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_customuser_cart_product_rating_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
